- name: test
  hosts: localhost
  gather_facts: false
  tasks:
    - name: e
      set_fact:
        hpeadmin_b64: "{{ hpeadmin | b64encode }}"

    - name: p
      debug:
        msg: "{{ hpeadmin_b64 }}"